updates

diff --git a/.github/workflows/apigee-deploy.yaml b/.github/workflows/apigee-deploy.yaml
--- a/.github/workflows/apigee-deploy.yaml
+++ b/.github/workflows/apigee-deploy.yaml
@@ -15,6 +15,7 @@ jobs:
       name: ${{ steps.parse.outputs.name }}
       env: ${{ steps.parse.outputs.env }}
       rev: ${{ steps.parse.outputs.rev }}
+      sha: ${{ steps.lookup.outputs.sha }}
 
     # env:
     #   APIGEE_ORG: my-apigee-org
@@ -37,7 +38,7 @@ jobs:
           TAG="${GITHUB_REF_NAME}"
           echo "Tag: $TAG"
           # Regex: type/name/env/vX.Y.Z
-          if [[ "$TAG" =~ ^apigee/(apiproxy|sharedflow)/([^/]+)/(staging|qa|prod)/([0-9]+)$ ]]; then
+          if [[ "$TAG" =~ ^apigee/(apiproxy|sharedflow)/([^/]+)/(sit|prod)/([0-9]+)$ ]]; then
             TYPE="${BASH_REMATCH[1]}"
             NAME="${BASH_REMATCH[2]}"
             ENV="${BASH_REMATCH[3]}"
@@ -62,33 +63,79 @@ jobs:
           echo "Env: ${{ steps.parse.outputs.env }}"
           echo "Revision: ${{ steps.parse.outputs.rev }}"
 
-  deploy-dev:
+      - name: Get metadata
+        id: lookup
+        run: |
+          META_FILE="metadata/${{ steps.parse.outputs.type }}-${{ steps.parse.outputs.name }}-${{ steps.parse.outputs.rev }}.json"
+          if [[ ! -f "$META_FILE" ]]; then
+            echo "❌ Metadata file not found: $META_FILE"
+            exit 1
+          fi
+          SHA=$(jq -r '.sha' "$META_FILE")
+          REVISION=$(jq -r '.revision' "$META_FILE")
+          echo "sha=$SHA" >> $GITHUB_OUTPUT
+
+          echo "Metadata says: sha=$SHA revision=$REVISION"
+
+          if [[ "${{ steps.parse.outputs.rev }}" != "$REVISION" ]]; then
+            echo "⚠️ Warning: Tag revision (${{
+              steps.parse.outputs.rev
+            }}) does not match metadata revision ($REVISION)"
+          fi
+
+  deploy-sit:
     runs-on: ubuntu-latest
     needs: parse
-    if: ${{ needs.parse.outputs.env == 'dev' }}
-    environment: dev
+    if: ${{ needs.parse.outputs.env == 'sit' }}
+    environment: sit
     steps:
       - uses: actions/checkout@v4
-      # - uses: ./.github/actions/deploy-proxy
-      #   with:
-      #     proxy_name: ${{ needs.parse.outputs.name }}
-      #     environment: dev
-      #     project_id: my-dev-project
-      #     org: my-apigee-org
+        with:
+          ref: ${{ needs.parse.outputs.sha }}
+          fetch-depth: 0
 
-  # deploy-staging:
-  #   needs: parse
-  #   if: ${{ needs.parse.outputs.env == 'staging' }}
-  #   environment: staging
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/deploy-proxy
-  #       with:
-  #         proxy_name: ${{ needs.parse.outputs.name }}
-  #         environment: staging
-  #         project_id: my-staging-project
-  #         org: my-apigee-org
+      - name: Build Apigee proxy/sharedflow bundle
+        run: |
+          case "${{ needs.parse.outputs.type }}" in
+            apiproxy) BASE="apiproxies" ; COMMAND="apigeecli apis import";;
+            sharedflow) BASE="sharedflows" ; COMMAND="apigeecli sharedflows import";;
+            *) echo "❌ Unknown type"; exit 1 ;;
+          esac
+
+          mkdir bundle
+          cd $BASE/${{ needs.parse.outputs.name }}
+          zip -r ../../bundle/${{ needs.parse.outputs.name }}.zip ${{ needs.parse.outputs.type }}/
+          echo "Created ${{ needs.parse.outputs.name }}.zip"
+
+      - name: Authenticate to Google Cloud
+        id: auth
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: '${{ secrets.APIGEE_SA_KEY }}'
+
+      - name: Install Apigee CLI
+        run: |
+          curl -sLO https://github.com/apigee/apigeecli/releases/download/v2.15.0/apigeecli_v2.15.0_Linux_x86_64.zip
+          unzip apigeecli_v2.15.0_Linux_x86_64.zip
+          sudo mv apigeecli_v2.15.0_Linux_x86_64/apigeecli /usr/local/bin/
+    
+      - name: Import ApigeeX Proxy
+        id: import
+        run: |
+          $COMMAND --default-token -o ${{ vars.APIGEE_ORG }}  --folder ./bundle
+          # REVISION=$(apigeecli apis get --default-token -o "$APIGEE_X_ORG" --name ${{ needs.parse.outputs.name  }} | jq -r '.latestRevisionId')
+          # echo "revision=$REVISION" >> "$GITHUB_OUTPUT"          
+
+      # - name: Import proxy bundle
+      #   env:
+      #     APIGEE_ORG: ${{ vars.APIGEE_ORG }}
+      #     PROXY_NAME: ${{ steps.parse.outputs.proxy }}
+      #     APIGEE_TOKEN: ${{ secrets.APIGEE_TOKEN }}
+      #   run: |
+      #     apigeecli apis import --org "$APIGEE_ORG" --name "$PROXY_NAME" --source bundle.zip --token "$APIGEE_TOKEN"
+      #     REV=$(apigeecli apis list --org "$APIGEE_ORG" --name "$PROXY_NAME" --json --token "$APIGEE_TOKEN" | jq -r '.[].revision[-1]')
+      #     echo "Imported new revision $REV"
+
 
   deploy-prod:
     needs: parse
@@ -97,6 +144,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - uses: ./.github/actions/deploy-proxy
         with:
           org: ${{ vars.APIGEE_ORG}}
@@ -148,4 +196,5 @@ jobs:
   #           --env ${{ steps.parse.outputs.env }} \
   #           --org $APIGEE_ORG \
   #           --token "$(gcloud auth print-access-token)"
+
 
